### ISSUE TITLE
Display issues on mobile Firefox

### ISSUE THREAD

**Issue by energydev** [techlahoma/thunderplains-2018#6]
Jeff Blankenbiller mentioned to me that the ThunderPlains site doesn't display properly on mobile Firefox. His phone is Android with one of the later OS's. Apparently, he can't make the site smaller in order to view things like the rest of the schedule.

**Comment by kacollins** [comment]
Did #20 address this? I noticed that the site looks much better on mobile now. Thank you, @nolawill!

**Comment by vlucas** [comment]
I am going to close this. I think the changes from @nolawill fixed this.
